package main

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

const (
	accessLifetime  = 15 * time.Minute
	refreshLifetime = 30 * 24 * time.Hour
)

var errNotConfigured = errors.New("provider_not_configured")

type store struct{ pool *pgxpool.Pool }

type session struct {
	AccessToken  string
	RefreshToken string
	ExpiresIn    int64
	UserID       string
}

func openStore(ctx context.Context, dsn string) (*store, error) {
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		return nil, err
	}
	if err = pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, err
	}
	_, err = pool.Exec(ctx, `
CREATE TABLE IF NOT EXISTS jourvolt_users (
    id TEXT PRIMARY KEY,
    provider_sub TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS jourvolt_sessions (
    id BIGSERIAL PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES jourvolt_users(id) ON DELETE CASCADE,
    access_hash TEXT UNIQUE NOT NULL,
    refresh_hash TEXT UNIQUE NOT NULL,
    access_expires_at TIMESTAMPTZ NOT NULL,
    refresh_expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS jourvolt_auth_transactions (
    state_hash TEXT PRIMARY KEY,
    transaction_hash TEXT UNIQUE NOT NULL,
    nonce TEXT NOT NULL,
    terms_version TEXT,
    privacy_version TEXT,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS jourvolt_login_tickets (
    ticket_hash TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES jourvolt_users(id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS jourvolt_tesla_tokens (
    user_id TEXT PRIMARY KEY REFERENCES jourvolt_users(id) ON DELETE CASCADE,
    access_ciphertext TEXT NOT NULL,
    refresh_ciphertext TEXT NOT NULL,
    access_expires_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS jourvolt_user_consents (
    user_id TEXT PRIMARY KEY REFERENCES jourvolt_users(id) ON DELETE CASCADE,
    terms_version TEXT NOT NULL,
    privacy_version TEXT NOT NULL,
    accepted_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS jourvolt_vehicles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES jourvolt_users(id) ON DELETE CASCADE,
    provider_vehicle_id TEXT NOT NULL,
    vin_ciphertext TEXT NOT NULL,
    display_name TEXT NOT NULL,
    state TEXT NOT NULL,
    model TEXT,
    trim_badging TEXT,
    exterior_color TEXT,
    wheel_type TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, provider_vehicle_id)
);
ALTER TABLE jourvolt_auth_transactions ADD COLUMN IF NOT EXISTS terms_version TEXT;
ALTER TABLE jourvolt_auth_transactions ADD COLUMN IF NOT EXISTS privacy_version TEXT;`)
	if err != nil {
		pool.Close()
		return nil, err
	}
	return &store{pool: pool}, nil
}

func (s *store) close() { s.pool.Close() }

func hashToken(value string) string {
	sum := sha256.Sum256([]byte(value))
	return hex.EncodeToString(sum[:])
}

func randomToken() (string, error) {
	buf := make([]byte, 32)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return hex.EncodeToString(buf), nil
}

func (s *store) ensureUser(ctx context.Context, id string) error {
	_, err := s.pool.Exec(ctx, `
INSERT INTO jourvolt_users(id, provider_sub) VALUES ($1, $1)
ON CONFLICT (id) DO NOTHING`, id)
	return err
}

func (s *store) createSession(ctx context.Context, userID string) (session, error) {
	access, err := randomToken()
	if err != nil {
		return session{}, err
	}
	refresh, err := randomToken()
	if err != nil {
		return session{}, err
	}
	now := time.Now().UTC()
	_, err = s.pool.Exec(ctx, `
INSERT INTO jourvolt_sessions(user_id, access_hash, refresh_hash, access_expires_at, refresh_expires_at)
VALUES ($1, $2, $3, $4, $5)`, userID, hashToken(access), hashToken(refresh),
		now.Add(accessLifetime), now.Add(refreshLifetime))
	if err != nil {
		return session{}, err
	}
	return session{AccessToken: access, RefreshToken: refresh, ExpiresIn: int64(accessLifetime.Seconds()), UserID: userID}, nil
}

func (s *store) userForAccess(ctx context.Context, token string) (string, error) {
	var userID string
	err := s.pool.QueryRow(ctx, `
SELECT user_id FROM jourvolt_sessions
WHERE access_hash=$1 AND revoked_at IS NULL AND access_expires_at > now()`, hashToken(token)).Scan(&userID)
	if errors.Is(err, pgx.ErrNoRows) {
		return "", errors.New("session_required")
	}
	return userID, err
}

func (s *store) rotateSession(ctx context.Context, refreshToken string) (session, error) {
	access, err := randomToken()
	if err != nil {
		return session{}, err
	}
	newRefresh, err := randomToken()
	if err != nil {
		return session{}, err
	}
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return session{}, err
	}
	defer tx.Rollback(ctx)
	var userID string
	err = tx.QueryRow(ctx, `
SELECT user_id FROM jourvolt_sessions
WHERE refresh_hash=$1 AND revoked_at IS NULL AND refresh_expires_at > now()
FOR UPDATE`, hashToken(refreshToken)).Scan(&userID)
	if errors.Is(err, pgx.ErrNoRows) {
		return session{}, errors.New("refresh_required")
	}
	if err != nil {
		return session{}, err
	}
	now := time.Now().UTC()
	_, err = tx.Exec(ctx, `
UPDATE jourvolt_sessions SET access_hash=$1, refresh_hash=$2,
access_expires_at=$3, refresh_expires_at=$4
WHERE refresh_hash=$5`, hashToken(access), hashToken(newRefresh), now.Add(accessLifetime), now.Add(refreshLifetime), hashToken(refreshToken))
	if err != nil {
		return session{}, err
	}
	if err = tx.Commit(ctx); err != nil {
		return session{}, err
	}
	return session{AccessToken: access, RefreshToken: newRefresh, ExpiresIn: int64(accessLifetime.Seconds()), UserID: userID}, nil
}

func (s *store) revokeSession(ctx context.Context, accessToken string) error {
	_, err := s.pool.Exec(ctx, `
UPDATE jourvolt_sessions
SET revoked_at=COALESCE(revoked_at, now())
WHERE access_hash=$1`, hashToken(accessToken))
	return err
}

func (s *store) deleteUser(ctx context.Context, userID string) error {
	_, err := s.pool.Exec(ctx, `DELETE FROM jourvolt_users WHERE id=$1`, userID)
	return err
}

type vehicle struct {
	ID            int    `json:"id"`
	DisplayName   string `json:"displayName"`
	State         string `json:"state"`
	BatteryLevel  int    `json:"batteryLevel,omitempty"`
	Source        string `json:"source"`
	Model         string `json:"-"`
	TrimBadging   string `json:"-"`
	ExteriorColor string `json:"-"`
	WheelType     string `json:"-"`
}

type provider interface {
	Vehicles(context.Context, string) ([]vehicle, error)
	Status(context.Context, string, int) (vehicleStatus, error)
}

type vehicleStatus struct {
	ObservedAt              time.Time
	DisplayName             string
	State                   string
	Odometer                *float64
	Healthy                 *bool
	Locked                  *bool
	SentryMode              *bool
	WindowsOpen             *bool
	DoorsOpen               *bool
	TrunkOpen               *bool
	FrunkOpen               *bool
	IsUserPresent           *bool
	CenterDisplayState      *string
	Version                 *string
	BatteryLevel            *int
	UsableBatteryLevel      *int
	EstimatedBatteryRange   *float64
	RatedBatteryRange       *float64
	IdealBatteryRange       *float64
	PluggedIn               *bool
	ChargingState           *string
	ChargeEnergyAdded       *float64
	ChargeLimitSOC          *int
	ChargePortDoorOpen      *bool
	ChargerActualCurrent    *int
	ChargerPhases           *int
	ChargerPower            *int
	ChargerVoltage          *int
	ChargeCurrentRequest    *int
	ChargeCurrentRequestMax *int
	TimeToFullCharge        *float64
	ShiftState              *string
	Power                   *int
	Speed                   *int
	Heading                 *int
	IsClimateOn             *bool
	InsideTemp              *float64
	OutsideTemp             *float64
	IsPreconditioning       *bool
	Source                  string
}

type mockProvider struct{}

func (mockProvider) Vehicles(context.Context, string) ([]vehicle, error) {
	return []vehicle{{
		ID: 1, DisplayName: "Development Model 3", State: "charging", BatteryLevel: 76,
		Source: "mock_fixture", Model: "3", TrimBadging: "Development",
		ExteriorColor: "Pearl White", WheelType: "Aero",
	}}, nil
}

func (mockProvider) Status(context.Context, string, int) (vehicleStatus, error) {
	charging := "Charging"
	return vehicleStatus{
		ObservedAt: time.Now().UTC(), DisplayName: "Development Model 3", State: "charging",
		Healthy: boolPointer(true), Locked: boolPointer(true), SentryMode: boolPointer(false),
		BatteryLevel: intPointer(76), UsableBatteryLevel: intPointer(76),
		PluggedIn: boolPointer(true), ChargingState: &charging, ChargeLimitSOC: intPointer(80),
		Source: "mock_fixture",
	}, nil
}

type unconfiguredProvider struct{}

func (unconfiguredProvider) Vehicles(context.Context, string) ([]vehicle, error) {
	return nil, errNotConfigured
}
func (unconfiguredProvider) Status(context.Context, string, int) (vehicleStatus, error) {
	return vehicleStatus{}, errNotConfigured
}

type routingProvider struct {
	mock  provider
	fleet provider
}

func (p routingProvider) selectProvider(userID string) provider {
	if userID == "mock-user" && p.mock != nil {
		return p.mock
	}
	if p.fleet != nil {
		return p.fleet
	}
	return unconfiguredProvider{}
}

func (p routingProvider) Vehicles(ctx context.Context, userID string) ([]vehicle, error) {
	return p.selectProvider(userID).Vehicles(ctx, userID)
}

func (p routingProvider) Status(ctx context.Context, userID string, vehicleID int) (vehicleStatus, error) {
	return p.selectProvider(userID).Status(ctx, userID, vehicleID)
}

type app struct {
	store              *store
	mock               provider
	provider           provider
	oauth              *teslaOAuth
	mockEnabled        bool
	mockHistoryEnabled bool
	mode               string
}

func (a *app) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path == "/healthz" {
		a.json(w, http.StatusOK, map[string]any{
			"status": "ok", "mode": a.mode, "persistence": "postgres",
			"mock_history": a.mockHistoryEnabled,
		})
		return
	}
	if r.URL.Path == "/readyz" {
		a.readyz(w, r)
		return
	}
	if r.Method == http.MethodPost && r.URL.Path == "/v1/dev/mock-login" {
		if !a.mockEnabled {
			a.json(w, http.StatusNotFound, map[string]string{"error": "not_found"})
			return
		}
		a.mockLogin(w, r)
		return
	}
	if a.authRoute(w, r) {
		return
	}
	if r.Method == http.MethodPost && r.URL.Path == "/v1/session/refresh" {
		a.refresh(w, r)
		return
	}
	if r.Method == http.MethodPost && r.URL.Path == "/v1/session/logout" {
		a.logout(w, r)
		return
	}
	if r.Method == http.MethodDelete && r.URL.Path == "/v1/account" {
		a.deleteAccount(w, r)
		return
	}
	userID, ok := a.auth(w, r)
	if !ok {
		return
	}
	if r.URL.Path == "/v1/vehicles" {
		vehicles, err := a.provider.Vehicles(r.Context(), userID)
		if err != nil {
			a.providerError(w, err)
			return
		}
		a.json(w, http.StatusOK, map[string]any{"vehicles": vehicles})
		return
	}
	if strings.HasPrefix(r.URL.Path, "/v1/vehicles/") {
		a.vehicleResource(w, r, userID)
		return
	}
	a.compat(w, r, userID)
}

func (a *app) mockLogin(w http.ResponseWriter, r *http.Request) {
	if err := a.store.ensureUser(r.Context(), "mock-user"); err != nil {
		a.json(w, http.StatusInternalServerError, map[string]string{"error": "store_unavailable"})
		return
	}
	s, err := a.store.createSession(r.Context(), "mock-user")
	if err != nil {
		a.json(w, http.StatusInternalServerError, map[string]string{"error": "session_create_failed"})
		return
	}
	vehicles, _ := a.mock.Vehicles(r.Context(), s.UserID)
	a.json(w, http.StatusOK, map[string]any{
		"access_token": s.AccessToken, "refresh_token": s.RefreshToken,
		"expires_in": s.ExpiresIn, "user": map[string]string{"id": s.UserID}, "vehicles": vehicles,
	})
}

func (a *app) refresh(w http.ResponseWriter, r *http.Request) {
	token := bearerToken(r)
	if token == "" {
		var body struct {
			RefreshToken string `json:"refresh_token"`
		}
		_ = json.NewDecoder(r.Body).Decode(&body)
		token = body.RefreshToken
	}
	s, err := a.store.rotateSession(r.Context(), token)
	if err != nil {
		a.json(w, http.StatusUnauthorized, map[string]string{"error": err.Error()})
		return
	}
	a.json(w, http.StatusOK, map[string]any{"access_token": s.AccessToken, "refresh_token": s.RefreshToken, "expires_in": s.ExpiresIn})
}

func (a *app) logout(w http.ResponseWriter, r *http.Request) {
	token := bearerToken(r)
	if token == "" {
		a.json(w, http.StatusUnauthorized, map[string]string{"error": "session_required"})
		return
	}
	if err := a.store.revokeSession(r.Context(), token); err != nil {
		a.json(w, http.StatusInternalServerError, map[string]string{"error": "logout_failed"})
		return
	}
	a.json(w, http.StatusOK, map[string]string{"status": "logged_out"})
}

func (a *app) deleteAccount(w http.ResponseWriter, r *http.Request) {
	userID, ok := a.auth(w, r)
	if !ok {
		return
	}
	if err := a.store.deleteUser(r.Context(), userID); err != nil {
		a.json(w, http.StatusInternalServerError, map[string]string{"error": "account_delete_failed"})
		return
	}
	response := map[string]string{"status": "deleted"}
	if a.oauth != nil {
		if revokeURL := a.oauth.consentRevokeURL(); revokeURL != "" {
			response["tesla_consent_revoke_url"] = revokeURL
		}
	}
	a.json(w, http.StatusOK, response)
}

func (a *app) auth(w http.ResponseWriter, r *http.Request) (string, bool) {
	token := bearerToken(r)
	if token == "" {
		a.json(w, http.StatusUnauthorized, map[string]string{"error": "session_required"})
		return "", false
	}
	userID, err := a.store.userForAccess(r.Context(), token)
	if err != nil {
		a.json(w, http.StatusUnauthorized, map[string]string{"error": err.Error()})
		return "", false
	}
	return userID, true
}

func (a *app) compat(w http.ResponseWriter, r *http.Request, userID string) {
	path := strings.TrimSuffix(r.URL.Path, "/")
	switch {
	case path == "/api/ping" || path == "/api/readyz":
		a.json(w, http.StatusOK, map[string]string{"ping": "pong"})
	case path == "/api/matelink/v1/capabilities":
		features := []string{"live_status"}
		if a.hasMockHistory(userID) {
			features = append(features, "history_fixture")
		}
		a.json(w, http.StatusOK, map[string]any{"data": map[string]any{"adapter_version": "jourvolt-dev-api", "features": features}})
	case strings.HasPrefix(path, "/api/matelink/v1/cars/"):
		a.adapterResource(w, r, userID, path)
	case path == "/api/v1/globalsettings":
		a.json(w, http.StatusOK, map[string]any{"data": map[string]any{"settings": map[string]any{"teslamate_units": map[string]string{"unit_of_length": "km", "unit_of_temperature": "C"}}}})
	case path == "/api/v1/cars":
		a.cars(w, r, userID)
	case strings.HasPrefix(path, "/api/v1/cars/"):
		a.carResource(w, r, userID, path)
	default:
		a.json(w, http.StatusNotFound, map[string]string{"error": "not_found"})
	}
}

func (a *app) adapterResource(w http.ResponseWriter, r *http.Request, userID, path string) {
	parts := strings.Split(strings.TrimPrefix(path, "/api/matelink/v1/cars/"), "/")
	if len(parts) < 2 {
		a.json(w, http.StatusNotFound, map[string]string{"error": "vehicle_not_found"})
		return
	}
	carID, err := strconv.Atoi(parts[0])
	if err != nil {
		a.json(w, http.StatusNotFound, map[string]string{"error": "vehicle_not_found"})
		return
	}
	if !a.requireVehicle(w, r, userID, carID) {
		return
	}
	switch parts[1] {
	case "snapshot":
		a.status(w, r, userID, carID, true)
	case "parked":
		a.json(w, http.StatusOK, map[string]any{"data": nil, "error": "history_not_collected"})
	default:
		a.json(w, http.StatusNotFound, map[string]string{"error": "not_found"})
	}
}

func (a *app) cars(w http.ResponseWriter, r *http.Request, userID string) {
	vehicles, err := a.provider.Vehicles(r.Context(), userID)
	if err != nil {
		a.providerError(w, err)
		return
	}
	items := make([]map[string]any, 0, len(vehicles))
	driveCount, chargeCount := 0, 0
	if a.hasMockHistory(userID) {
		driveCount, chargeCount = len(mockDriveFixtures()), len(mockChargeFixtures())
	}
	for _, v := range vehicles {
		items = append(items, map[string]any{
			"car_id": v.ID, "name": v.DisplayName,
			"car_details":     map[string]any{"model": emptyAsNil(v.Model), "trim_badging": emptyAsNil(v.TrimBadging), "efficiency": nil},
			"car_exterior":    map[string]any{"exterior_color": emptyAsNil(v.ExteriorColor), "wheel_type": emptyAsNil(v.WheelType)},
			"teslamate_stats": map[string]any{"total_charges": chargeCount, "total_drives": driveCount},
		})
	}
	a.json(w, http.StatusOK, map[string]any{"data": map[string]any{"cars": items}})
}

func (a *app) carResource(w http.ResponseWriter, r *http.Request, userID, path string) {
	parts := strings.Split(strings.TrimPrefix(path, "/api/v1/cars/"), "/")
	if len(parts) == 0 || parts[0] == "" {
		a.json(w, http.StatusNotFound, map[string]string{"error": "not_found"})
		return
	}
	carID, err := strconv.Atoi(parts[0])
	if err != nil {
		a.json(w, http.StatusNotFound, map[string]string{"error": "vehicle_not_found"})
		return
	}
	if !a.requireVehicle(w, r, userID, carID) {
		return
	}
	if len(parts) == 1 {
		a.cars(w, r, userID)
		return
	}
	switch parts[1] {
	case "status":
		a.status(w, r, userID, carID, false)
	case "charges":
		if len(parts) > 2 && parts[2] == "current" {
			a.json(w, http.StatusOK, map[string]any{"data": nil, "error": "No active charging in progress."})
		} else if len(parts) > 2 && a.hasMockHistory(userID) {
			a.mockChargeDetail(w, parts[2])
		} else if a.hasMockHistory(userID) {
			a.json(w, http.StatusOK, map[string]any{"data": map[string]any{
				"charges": paginateFixture(mockChargeFixtures(), r), "meta": a.historyMeta(userID),
			}})
		} else {
			a.json(w, http.StatusOK, map[string]any{"data": map[string]any{
				"charges": []any{}, "meta": a.historyMeta(userID),
			}})
		}
	case "drives":
		if len(parts) > 2 && a.hasMockHistory(userID) {
			a.mockDriveDetail(w, parts[2])
		} else if a.hasMockHistory(userID) {
			a.json(w, http.StatusOK, map[string]any{"data": map[string]any{
				"drives": paginateFixture(mockDriveFixtures(), r), "meta": a.historyMeta(userID),
			}})
		} else {
			a.json(w, http.StatusOK, map[string]any{"data": map[string]any{
				"drives": []any{}, "meta": a.historyMeta(userID),
			}})
		}
	case "battery-health":
		a.json(w, http.StatusOK, map[string]any{"data": map[string]any{
			"battery_health": nil, "meta": a.unsupportedMeta(userID),
		}})
	case "updates":
		a.json(w, http.StatusOK, map[string]any{"data": map[string]any{"updates": []any{}}})
	default:
		a.json(w, http.StatusNotFound, map[string]string{"error": "not_found"})
	}
}

func (a *app) vehicleResource(w http.ResponseWriter, r *http.Request, userID string) {
	parts := strings.Split(strings.TrimPrefix(r.URL.Path, "/v1/vehicles/"), "/")
	if len(parts) < 1 {
		a.json(w, http.StatusNotFound, map[string]string{"error": "vehicle_not_found"})
		return
	}
	vehicleID, err := strconv.Atoi(parts[0])
	if err != nil || !a.requireVehicle(w, r, userID, vehicleID) {
		return
	}
	if len(parts) == 2 && parts[1] == "status" {
		a.status(w, r, userID, vehicleID, false)
		return
	}
	a.json(w, http.StatusNotFound, map[string]string{"error": "not_found"})
}

func (a *app) requireVehicle(w http.ResponseWriter, r *http.Request, userID string, vehicleID int) bool {
	owned, err := a.vehicleOwned(r.Context(), userID, vehicleID)
	if err != nil {
		a.providerError(w, err)
		return false
	}
	if owned {
		return true
	}
	a.json(w, http.StatusNotFound, map[string]string{"error": "vehicle_not_found"})
	return false
}

func (a *app) vehicleOwned(ctx context.Context, userID string, vehicleID int) (bool, error) {
	vehicles, err := a.provider.Vehicles(ctx, userID)
	if err != nil {
		return false, err
	}
	for _, vehicle := range vehicles {
		if vehicle.ID == vehicleID {
			return true, nil
		}
	}
	return false, nil
}

func (a *app) status(w http.ResponseWriter, r *http.Request, userID string, carID int, snapshot bool) {
	providerStatus, err := a.provider.Status(r.Context(), userID, carID)
	if err != nil {
		a.providerError(w, err)
		return
	}
	status := map[string]any{
		"display_name": providerStatus.DisplayName,
		"state":        providerStatus.State,
		"state_since":  nil,
		"odometer":     providerStatus.Odometer,
		"car_status": map[string]any{
			"healthy": providerStatus.Healthy, "locked": providerStatus.Locked,
			"sentry_mode": providerStatus.SentryMode, "windows_open": providerStatus.WindowsOpen,
			"doors_open": providerStatus.DoorsOpen, "trunk_open": providerStatus.TrunkOpen,
			"frunk_open": providerStatus.FrunkOpen, "is_user_present": providerStatus.IsUserPresent,
			"center_display_state": providerStatus.CenterDisplayState,
		},
		"car_versions": map[string]any{"version": providerStatus.Version, "update_available": nil, "update_version": nil},
		"driving_details": map[string]any{
			"shift_state": providerStatus.ShiftState, "power": providerStatus.Power,
			"speed": providerStatus.Speed, "heading": providerStatus.Heading, "elevation": nil,
		},
		"climate_details": map[string]any{
			"is_climate_on": providerStatus.IsClimateOn, "inside_temp": providerStatus.InsideTemp,
			"outside_temp": providerStatus.OutsideTemp, "is_preconditioning": providerStatus.IsPreconditioning,
		},
		"battery_details": map[string]any{
			"battery_level": providerStatus.BatteryLevel, "usable_battery_level": providerStatus.UsableBatteryLevel,
			"est_battery_range": providerStatus.EstimatedBatteryRange, "rated_battery_range": providerStatus.RatedBatteryRange,
			"ideal_battery_range": providerStatus.IdealBatteryRange,
		},
		"charging_details": map[string]any{
			"plugged_in": providerStatus.PluggedIn, "charging_state": providerStatus.ChargingState,
			"charge_energy_added": providerStatus.ChargeEnergyAdded, "charge_limit_soc": providerStatus.ChargeLimitSOC,
			"charge_port_door_open":  providerStatus.ChargePortDoorOpen,
			"charger_actual_current": providerStatus.ChargerActualCurrent, "charger_phases": providerStatus.ChargerPhases,
			"charger_power": providerStatus.ChargerPower, "charger_voltage": providerStatus.ChargerVoltage,
			"charge_current_request":     providerStatus.ChargeCurrentRequest,
			"charge_current_request_max": providerStatus.ChargeCurrentRequestMax,
			"time_to_full_charge":        providerStatus.TimeToFullCharge,
		},
	}
	units := map[string]string{"unit_of_length": "km", "unit_of_pressure": "bar", "unit_of_temperature": "C"}
	if snapshot {
		a.json(w, http.StatusOK, map[string]any{"data": map[string]any{
			"status": status, "units": units, "observed_at": providerStatus.ObservedAt.Format(time.RFC3339),
			"source":        providerStatus.Source,
			"field_sources": map[string]string{"battery_level": providerStatus.Source, "charging_state": providerStatus.Source},
		}})
		return
	}
	a.json(w, http.StatusOK, map[string]any{"data": map[string]any{"status": status, "units": units}})
}

func (a *app) providerError(w http.ResponseWriter, err error) {
	switch {
	case errors.Is(err, errNotConfigured):
		a.json(w, http.StatusServiceUnavailable, map[string]string{"error": "provider_not_configured"})
	case errors.Is(err, errTeslaReauthorization):
		a.json(w, http.StatusUnauthorized, map[string]string{"error": "tesla_reauthorization_required"})
	case errors.Is(err, errTeslaRateLimited):
		w.Header().Set("Retry-After", "60")
		a.json(w, http.StatusTooManyRequests, map[string]string{"error": "tesla_rate_limited"})
	case errors.Is(err, errVehicleNotFound):
		a.json(w, http.StatusNotFound, map[string]string{"error": "vehicle_not_found"})
	case errors.Is(err, errTeslaUnavailable):
		a.json(w, http.StatusServiceUnavailable, map[string]string{"error": "tesla_temporarily_unavailable"})
	default:
		a.json(w, http.StatusBadGateway, map[string]string{"error": "upstream_unavailable"})
	}
}

func emptyAsNil(value string) any {
	if value == "" {
		return nil
	}
	return value
}

func bearerToken(r *http.Request) string {
	value := r.Header.Get("Authorization")
	if len(value) > len("Bearer ") && strings.EqualFold(value[:len("Bearer ")], "Bearer ") {
		return strings.TrimSpace(value[len("Bearer "):])
	}
	return ""
}

func (a *app) json(w http.ResponseWriter, status int, payload any) {
	data, err := json.Marshal(payload)
	if err != nil {
		http.Error(w, `{"error":"serialization_failed"}`, http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Cache-Control", "no-store")
	w.WriteHeader(status)
	_, _ = w.Write(data)
}

func (a *app) readyz(w http.ResponseWriter, r *http.Request) {
	if a.store == nil || a.store.pool == nil {
		a.json(w, http.StatusServiceUnavailable, map[string]string{"status": "not_ready"})
		return
	}
	ctx, cancel := context.WithTimeout(r.Context(), 2*time.Second)
	defer cancel()
	if err := a.store.pool.Ping(ctx); err != nil {
		a.json(w, http.StatusServiceUnavailable, map[string]string{"status": "not_ready"})
		return
	}
	a.json(w, http.StatusOK, map[string]any{
		"status": "ok", "mode": a.mode, "persistence": "postgres",
	})
}

func main() {
	ctx := context.Background()
	dsn := os.Getenv("DATABASE_URL")
	if dsn == "" {
		dsn = "postgres://jourvolt:jourvolt@127.0.0.1:5432/jourvolt?sslmode=disable"
	}
	store, err := openStore(ctx, dsn)
	if err != nil {
		log.Fatalf("jourvolt store: %v", err)
	}
	defer store.close()
	enableMock, err := loadBool(os.Getenv, "JOURVOLT_ENABLE_MOCK", false)
	if err != nil {
		log.Fatal(err)
	}
	enableMockHistory, err := loadBool(os.Getenv, "JOURVOLT_ENABLE_MOCK_HISTORY", false)
	if err != nil {
		log.Fatal(err)
	}
	if enableMockHistory && !enableMock {
		log.Fatal("JOURVOLT_ENABLE_MOCK_HISTORY requires JOURVOLT_ENABLE_MOCK=true")
	}
	teslaSettings, err := loadTeslaConfig(os.Getenv)
	if err != nil {
		log.Fatal(err)
	}
	httpClient := &http.Client{Timeout: 20 * time.Second}
	mock := mockProvider{}
	dataProvider := provider(unconfiguredProvider{})
	mode := "unconfigured"
	var oauth *teslaOAuth
	if teslaSettings != nil {
		cipher, err := newTokenCipher(teslaSettings.TokenKey)
		if err != nil {
			log.Fatal(err)
		}
		tokenManager := &teslaTokenManager{store: store, cipher: cipher, config: teslaSettings, client: httpClient}
		fleet := &fleetProvider{
			store: store, tokens: tokenManager, cipher: cipher,
			client: httpClient, baseURL: teslaSettings.FleetAPIBase,
		}
		oauth = newTeslaOAuth(teslaSettings, store, cipher, httpClient)
		dataProvider = fleet
		mode = "fleet"
		if enableMock {
			dataProvider = routingProvider{mock: mock, fleet: fleet}
			mode = "fleet_with_debug_mock"
		}
	} else if enableMock {
		dataProvider = mock
		mode = "mock_only"
	}
	a := &app{
		store: store, mock: mock, provider: dataProvider, oauth: oauth,
		mockEnabled: enableMock, mockHistoryEnabled: enableMockHistory, mode: mode,
	}
	addr := os.Getenv("LISTEN_ADDR")
	if addr == "" {
		addr = ":8080"
	}
	log.Printf("jourvolt api listening on %s mode=%s", addr, mode)
	if err := http.ListenAndServe(addr, a); err != nil {
		log.Fatal(fmt.Errorf("listen: %w", err))
	}
}
